version: '3'

networks:
  motus-network:
    external:
      name: 'motus_network'

services:
  redis_auth:
    image: redis
    container_name: redis_auth
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=redis
    ports:
      - "6379:6379"

  auth_service:
    container_name: auth_service
    build: ./auth
    ports:
      - "5001:5001"
    depends_on:
      - redis_auth

  redis_score:
    image: redis
    container_name: redis_score
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=redis
    ports:
      - "6380:6379" 

  score_service:
    container_name: score_service
    build: ./score
    ports:
      - "4001:4001"
    depends_on:
      - redis_score

  game_service:
    container_name: game_service
    build: ./motus
    ports:
      - "3001:3001"




 