version: '3'

networks:
  motus-network:
    external:
      name: 'motus_network'


services:
  redis_motus:
    image: redis
    container_name: redis_motus
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=redis
    networks:
      - motus-network
    ports:
      - "6379:6379"





